DROP TABLE IF EXISTS readings;

CREATE TABLE readings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  time_inserted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sensor_type TEXT NOT NULL,
  plant_id INTEGER,
  reading REAL NOT NULL
);
